### ISSUE TITLE
Colors-List

### ISSUE THREAD

**Issue by pung-one** [pung-one/capstone-project#2]
## Value Proposition

**As a Dewsigner
**I want to see a list of colors
**so that i can choose one and click on it. 
​

## Description

![Untitled-2023-01-11-0955](https://user-images.githubusercontent.com/86004796/222692449-c17084d1-21ab-48ef-b6d1-9723a4996ffb.png)

​

## Acceptance Criteria

- [ ]  display a scrollable list of the 159 sanzo colors
- [ ] each list item consists of a box showing its color
- [ ] each color works as a link
- [ ] each color has a name
      ​

## Tasks

- [ ] fetch color list in api
- [ ] create an ul-component
- [ ] dynamically render a list of the fetched colors
- [ ] each list element is a Link-component
      ​

## Complexity

... M

**Comment by christopher-koch** [comment]
very detailed - excellent job!
