### ISSUE TITLE
color-page

### ISSUE THREAD

**Issue by pung-one** [pung-one/capstone-project#3]
## Value Proposition

**As a designer.
**I want to see a list of color combinations which contain at least one specific color  
**So that i can choose one of them to use it in a project
​

## Description

![color-page](https://user-images.githubusercontent.com/86004796/222695432-c3b8ca72-1791-4c5c-b799-d87aee6b6fd1.png)

​

## Acceptance Criteria

- [ ] when clicking on a color, render a scrollable list of all its combinations 
- [ ] be able to click on a combination
- [ ] the upper third of the screen shows a box with the background-color of the current color and as heading the name of the current color
- [ ] the other two thirds show a list of sanzo combinations with the current color
- [ ] each combination consists of a row of boxes 
- [ ] each combination has a number
- [ ] each combination has a bookmark-button      ​

## Tasks

- [ ] dynamically render the upper box with heading and list with hex, cmyk, hsl and rbg values
- [ ] iterate through colors to find the combinations that contain the current color
- [ ] dynamically render a list of those combinations
- [ ] each list item has a bookmark-button
- [ ] each list element dynamically renders the color-boxes as flex items
- [ ] each box has the background-color of one the colors
      ​

## Complexity

... L

**Comment by christopher-koch** [comment]
also very detailed - amazing work.
