### ISSUE TITLE
Accessibility

### ISSUE THREAD

**Issue by pung-one** [pung-one/capstone-project#34]
## Value Proposition

**As a user** 
**I want to access all parts of the website** 
**so that can experience it independent from my ability/disability** 
​

## Description

Add aria-labels and aria-roles. Also replace non semantic html tags with semantic ones
​

## Acceptance Criteria

- [ ] website should be as accessible as possible
      ​

## Tasks

- [ ] run lighthouse test in dev-tools
- [ ] check every page and component for missing aria-labels and aria-roles
- [ ] check for non-semantic html tags and replace them

## Complexity

-M
