### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by pung-one** [pung-one/capstone-project#35]
## Value Proposition

**As a developer** 
**I want to know if components or functions work as expected** 
**so that i can be sure to use them as planned**
​

## Description

Write tests for components and functions.
​

## Acceptance Criteria

- [ ] tests for 3 components should pass
- [ ] tests for the 2 utility functions should pass
      ​

## Tasks

- [ ] write tests for 3 components
- [ ] write tests for the 2 utility functions
      ​

## Complexity

-M
