### ISSUE TITLE
palettes-list

### ISSUE THREAD

**Issue by pung-one** [pung-one/capstone-project#4]
## Value Proposition

- As a designer  
- I want to see a list of color combinations
- so that i can choose one of them to use it in a project
​

## Description

![palettes-list](https://user-images.githubusercontent.com/86004796/222697610-a40191fe-f976-4f04-9767-afa43d2b8adb.png)

​

## Acceptance Criteria

- [ ] show a scrollable list of all sanzo combinations
- [ ] be able to click on a combination
- [ ] be able to bookmark a combination
- [ ] each list item consists of colored boxes
      ​

## Tasks

- [ ] dynamically render the list of combinations
- [ ] each list item has a number and a bookmark-button
- [ ] each list item renders colored boxes as flex items
      ​

## Complexity

- L

**Comment by christopher-koch** [comment]
totally fascinating work Mr. Streber! 🤡
