### ISSUE TITLE
palette-list

### ISSUE THREAD

**Issue by pung-one** [pung-one/capstone-project#5]
## Value Proposition

- As a designer 
**I want to** ... (describe the goal)  
**so that** ... (describe the reason)  
​

## Description

... (Wireframe, scribble, design or text)
​

## Acceptance Criteria

- [ ] Describe every scenarios in detail
- [ ] e.g. all inputs are required, show warning if empty.
- [ ] ...
      ​

## Tasks

- [ ] list the tasks that need to be performend within the dev team
- [ ] e.g. Components, Storybook, testing
- [ ] ...
      ​

## Complexity

... (T-Shirt Sizes XS to XL)

**Comment by Marcel-FR** [comment]
Nicely done! I earned 1000€ in 3 minutes though.
