### ISSUE TITLE
homepage-with-buttons

### ISSUE THREAD

**Issue by pung-one** [pung-one/capstone-project#6]
## Value Proposition

**As a designer**
**I want a homepage where i find different options to choose color or combination the lazy way**
**So that i can quickly find colors for my project**
​

## Description

![home-page-with-buttons](https://user-images.githubusercontent.com/86004796/222712179-ae9a24f5-d342-4077-89fe-50b2dff6237e.png)

​

## Acceptance Criteria

- [ ] show the app name at the top
- [ ] show three buttons:
    1. pick a color from color picker
    2. pick a random color
    3. pick a random color combination
      ​

## Tasks

- [ ] implement button which links to color picker tool
- [ ] write logic to compare picked color with all colors from list and finds most similar color
- [ ] implement button which links to a random color from list
- [ ] implement button which links to a random palette from list
      ​

## Complexity

- XL

**Comment by Marcel-FR** [comment]
Very good!
