### ISSUE TITLE
nav-bar

### ISSUE THREAD

**Issue by pung-one** [pung-one/capstone-project#7]
## Value Proposition

**As a designer**
**I want a navigation bar to switch between homepage, lists and bookmarks**
**So that i have access to all functions of the app**
​

## Description

![nav-bar](https://user-images.githubusercontent.com/86004796/222713666-dc12d549-3be2-4aef-9c5b-775243ab687d.png)

​

## Acceptance Criteria

- [ ] show nav-bar at the bottom
- [ ] show symbols which link to:
    1. homepage
    2. lists
    3. bookmarks
      ​

## Tasks

- [ ] build Layout component which is shown on all pages
- [ ] find symbols for each link      ​

## Complexity

- M

**Comment by Marcel-FR** [comment]
LGTM!
